name: C Project

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compilar programa principal
        run: |
          gcc ./arquivo-ox.c -o arquivo-ox

      - name: Executar programa
        run: |
          ./arquivo-ox skibidiArquivo.txt O O O X X X O O O

      - name: Verificar arquivo gerado
        run: |
          test -f skibidiArquivo.txt

      - name: Compilar testes
        run: |
          gcc test_arquivo-ox.c -o test_arquivo-ox

      - name: Executar testes
        run: |
          ./test_arquivo-ox
